<script>
 import {tick} from 'svelte';
 import {checklistReady,checklistSetup,advanceChecklist} from '../lib/guided-install.mjs';
 let page=$state('start'),answers=$state({game:null,sota:null,bodycam:null,devices:null,looting:null}),current=$state(0),question=$state(0),skippedMags=$state(false),panel,stepNodes=[];
 const questions=[['game','Which modpack do you use?','Select the installation you will play with.','MOD'],['sota','Do you use SOTA UI?','Choose the matching inventory interface and icon patch.','UI'],['bodycam','Do you use Bodycam?','Choose the compatible engine package.','CAM'],['devices','Do you use Wearable Devices?','Include support for the separate Wearable Devices mod.','WD'],['looting','Do you use Looting Takes Time Redux?','Include the optional Tarkov-like corpse looting patch.','LT']];
 const titles={mod:'Install Squared Away',engine:'Install the matching engine',mags:'Install magazine support (optional)',zona:'Check ZONA recipes and dependencies',anomaly:'Check your Anomaly setup',sota:'Choose your UI option',hd:'Install the correct icon framework',devices:'Enable Wearable Devices support',looting:'Set up corpse looting',order:'Check your load order',newgame:'New Game'};
 let ready=$derived(checklistReady(answers));
 let steps=$derived(window.InstallationGuide.steps(checklistSetup(answers)));
 async function show(next){page=next;await tick();panel?.scrollIntoView({block:'start',behavior:'smooth'});}
 function answer(key,value){answers[key]=value;current=0;skippedMags=false;if(question<questions.length-1)question++;else if(checklistReady(answers))show('steps');}
 async function check(index,value){if(!value&&steps[index][0]==='mags')skippedMags=false;current=advanceChecklist(current,index,value,steps.length);await tick();if(current<steps.length)stepNodes[current]?.scrollIntoView({block:'center',behavior:'smooth'});}
</script>
<section class="install-wizard" bind:this={panel} aria-label="Guided installation">
{#if page==='start'}
 <div class="wizard-invite"><div><p class="flow-kicker">YOUR SETUP. YOUR CHECKLIST.</p><h2>Install it for your modlist.</h2><p>Answer five quick questions. Get the right patches and follow the installation one step at a time.</p></div><button class="wizard-primary" onclick={()=>show('questions')}>Get my installation checklist →</button></div>
{:else if page==='questions'}
 <div class="wizard-heading"><div><p class="flow-kicker">01 / YOUR MODLIST</p><h2>What do you play with?</h2></div><button class="wizard-link" onclick={()=>show('start')}>Close guide</button></div>
 <div class="wizard-questions">{#each questions.slice(question,question+1) as [key,title,description,badge] (key)}<div class="wizard-question" class:answered={answers[key]!==null}><span class="wizard-badge">{badge}</span><h3>{title}</h3><p>{description}</p><div class="wizard-answers" role="group" aria-label={title}>{#if key==='game'}{#each [['gamma','GAMMA'],['zona','ZONA'],['anomaly','Anomaly 1.5.3']] as [id,name]}<button aria-pressed={answers.game===id} class:chosen={answers.game===id} onclick={()=>answer('game',id)}>{name}</button>{/each}{:else}<button aria-pressed={answers[key]===true} class:chosen={answers[key]===true} onclick={()=>answer(key,true)}>Yes</button><button aria-pressed={answers[key]===false} class:chosen={answers[key]===false} onclick={()=>answer(key,false)}>No</button>{/if}</div></div>{/each}</div>
 <div class="wizard-footer"><span>Question {question+1} of {questions.length}</span>{#if question>0}<button class="wizard-link" onclick={()=>question--}>← Previous question</button>{/if}</div>
{:else}
 <div class="wizard-heading"><div><p class="flow-kicker">02 / INSTALLATION</p><h2>{current===steps.length?'You’re squared away.':'One step at a time.'}</h2><p>{current} of {steps.length} steps completed · {answers.game==='zona'?'ZONA':answers.game==='gamma'?'GAMMA':'Anomaly 1.5.3'}{answers.sota?' · SOTA UI':''}{answers.bodycam?' · Bodycam':''}</p></div><button class="wizard-link" onclick={()=>{question=0;show('questions');}}>Change my answers</button></div>
 <progress max={steps.length} value={current} aria-label="Installation progress"></progress>
 <div class="wizard-checklist">{#each steps as [id,text],i}<article bind:this={stepNodes[i]} class="wizard-step" class:active={i===current} class:complete={i<current} class:locked={i>current} aria-current={i===current?'step':undefined}><span class="wizard-step-number">{i<current?(id==='mags'&&skippedMags?'—':'✓'):String(i+1).padStart(2,'0')}</span><div><h3>{titles[id]||id}{#if id==='mags'}<span class="step-tag recommended">Recommended</span>{:else if id==='newgame'}<span class="step-tag important">Important</span>{/if}</h3><p>{text}</p>{#if i===current}<div class="step-actions"><label class="wizard-confirm"><input type="checkbox" checked={false} onchange={e=>check(i,e.currentTarget.checked)}/>I’ve completed this step</label>{#if id==='mags'&&answers.game!=='zona'}<a href="https://discord.com/channels/912320241713958912/1322655858240262304/1524208180135989459" target="_blank" rel="noreferrer">Download magazine mod ↗</a><button class="wizard-link" onclick={()=>{skippedMags=true;check(i,true);}}>Skip optional step</button>{/if}</div>{:else if i<current}{#if id==='mags'&&skippedMags}<small>Skipped · optional support</small>{/if}<button class="wizard-link" onclick={()=>check(i,false)}>Revisit this step</button>{:else}<small>Complete the previous step to continue.</small>{/if}</div></article>{/each}</div>
 {#if current===steps.length}<div class="wizard-complete" role="status"><h3>Checklist complete</h3><p>Your installation steps are checked off. Launch the game and test your setup.</p><button class="wizard-link" onclick={()=>{current=0;show('steps');}}>Start the checklist again</button></div>{/if}
 <div class="wizard-footer"><a href="#downloads" target="_blank" rel="noreferrer">Open mod and engine downloads ↗</a>{#if answers.game!=='zona'}<a href="https://discord.com/channels/912320241713958912/1322655858240262304/1524208180135989459" target="_blank" rel="noreferrer">Magazine mod ↗</a>{/if}</div>
{/if}
</section>
<style>
.install-wizard{margin:30px 0;border:5px solid transparent;border-image:url('/zonebench-preview/assets/field-kit/frame.svg') 12 / 5px / 0 stretch;background:#171d17;padding:26px;scroll-margin-top:125px}.wizard-invite,.wizard-heading{display:flex;align-items:center;justify-content:space-between;gap:25px}.install-wizard h2{font-size:25px;font-weight:500;margin:12px 0}.install-wizard p{color:var(--dim);font-size:13px;line-height:1.8}.wizard-invite p{max-width:620px}.wizard-primary{border:1px solid #dcb88e;background:#dcb88e;color:#161c16;padding:15px 20px;font:inherit;font-size:13px;cursor:pointer;white-space:nowrap}.wizard-link{border:0;background:none;color:var(--hot);font:inherit;font-size:12px;cursor:pointer;padding:7px 0}.wizard-questions{display:grid;grid-template-columns:minmax(0,1fr);max-width:540px;margin:22px auto 0}.wizard-question{padding:20px 18px 0;background:#101610;border:1px solid #49513f;display:flex;flex-direction:column}.wizard-question.answered{border-color:#8c9471}.wizard-badge{width:38px;height:34px;display:grid;place-items:center;border:1px solid #535f48;color:#b2c399;font-size:11px}.wizard-question h3{font-size:17px;line-height:1.5;font-weight:500}.wizard-question p{flex:1;margin-top:0}.wizard-answers{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));margin:10px -18px 0}.wizard-answers button{padding:13px;border:1px solid #434d39;background:#20291c;color:var(--ink);cursor:pointer;font:inherit}.wizard-answers button.chosen{background:#dcb88e;color:#182016;border-color:#dcb88e}.wizard-footer{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:15px;margin-top:23px;font-size:12px;color:var(--dim)}.wizard-footer a{color:var(--hot)}progress{width:100%;height:6px;margin:18px 0;accent-color:#aabd8e}.wizard-checklist{display:grid;gap:12px}.wizard-step{display:flex;align-items:flex-start;gap:20px;padding:22px;background:#111810;border:1px solid #454d3d}.wizard-step-number{flex-shrink:0;color:#9dae86;font-size:18px;padding-top:4px}.wizard-step h3{margin:0;font-size:18px;font-weight:500}.wizard-step p{margin:10px 0}.wizard-step.active{border-color:#dcb88e;background:#252b20;box-shadow:inset 3px 0 #dcb88e}.wizard-step.locked{opacity:.38}.wizard-step.complete{opacity:.7}.wizard-step small{font-size:11px;color:var(--dim)}.wizard-confirm{display:flex;align-items:center;gap:12px;padding:12px 0 0;font-size:14px;color:var(--hot);cursor:pointer}.wizard-confirm input{width:19px;height:19px;accent-color:#dcb88e}.wizard-complete{padding:20px;border:1px solid #9cae80;background:#26301f;margin-top:20px}.wizard-heading>.wizard-link{flex-shrink:0}@media(max-width:900px){.wizard-invite{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.install-wizard{padding:16px}.wizard-questions{grid-template-columns:1fr}.wizard-heading{align-items:flex-start;flex-direction:column}.wizard-primary{white-space:normal}.wizard-step{gap:12px;padding:16px}}
.wizard-question{padding-top:26px}.wizard-question h3{font-size:22px}.wizard-answers button{padding:18px}.step-tag{display:inline-block;padding:4px 7px;margin-left:12px;font-size:10px;vertical-align:middle;letter-spacing:.05em;border:1px solid}.recommended{color:#bccda7;border-color:#6e8259;background:#33402b}.important{color:#e5afba;border-color:#a66273;background:#3a252b}.step-actions{display:flex;align-items:center;flex-wrap:wrap;gap:18px}.step-actions a{font-size:12px;color:var(--hot);padding-top:12px}.step-actions .wizard-link{padding-top:18px}
</style>
