<script>
 import {tick} from 'svelte';
 import {checklistReady,checklistSetup,advanceChecklist} from '../lib/guided-install.mjs';
 let page=$state('start'),answers=$state({game:null,sota:null,bodycam:null,devices:null,looting:null}),current=$state(0),panel,stepNodes=[];
 const questions=[['game','Do you use GAMMA?','Choose No for vanilla Anomaly 1.5.3.','G'],['sota','Do you use SOTA UI?','Choose the matching inventory interface and icon patch.','UI'],['bodycam','Do you use Bodycam?','Choose the compatible engine package.','CAM'],['devices','Do you use Wearable Devices?','Include support for the separate Wearable Devices mod.','WD'],['looting','Do you use Looting Takes Time Redux?','Include the optional Tarkov-like corpse looting patch.','LT']];
 const titles={mod:'Install Squared Away',engine:'Install the matching engine',mags:'Install magazine support',anomaly:'Check your Anomaly setup',sota:'Choose your UI option',hd:'Install the correct icon framework',devices:'Enable Wearable Devices support',looting:'Set up corpse looting',order:'Check your load order',newgame:'Choose the right save'};
 let ready=$derived(checklistReady(answers));
 let steps=$derived(window.InstallationGuide.steps(checklistSetup(answers)));
 async function show(next){page=next;await tick();panel?.scrollIntoView({block:'start',behavior:'smooth'});}
 function answer(key,value){const wasReady=ready;answers[key]=value;current=0;if(!wasReady&&checklistReady(answers))show('steps');}
 async function check(index,value){current=advanceChecklist(current,index,value,steps.length);await tick();if(current<steps.length)stepNodes[current]?.scrollIntoView({block:'center',behavior:'smooth'});}
</script>
<section class="install-wizard" bind:this={panel} aria-label="Guided installation">
{#if page==='start'}
 <div class="wizard-invite"><div><p class="flow-kicker">YOUR SETUP. YOUR CHECKLIST.</p><h2>Install it for your modlist.</h2><p>Answer five quick questions. Get the right patches and follow the installation one step at a time.</p></div><button class="wizard-primary" onclick={()=>show('questions')}>Get my installation checklist →</button></div>
{:else if page==='questions'}
 <div class="wizard-heading"><div><p class="flow-kicker">01 / YOUR MODLIST</p><h2>What do you play with?</h2><p>Choose Yes or No on each card. This uses your answers; it does not scan your installed mods.</p></div><button class="wizard-link" onclick={()=>show('start')}>Close guide</button></div>
 <div class="wizard-questions">{#each questions as [key,title,description,badge]}<div class="wizard-question" class:answered={answers[key]!==null}><span class="wizard-badge">{badge}</span><h3>{title}</h3><p>{description}</p><div class="wizard-answers" role="group" aria-label={title}><button aria-pressed={answers[key]===true} class:chosen={answers[key]===true} onclick={()=>answer(key,true)}>Yes</button><button aria-pressed={answers[key]===false} class:chosen={answers[key]===false} onclick={()=>answer(key,false)}>No</button></div></div>{/each}</div>
 <div class="wizard-footer"><span>{Object.values(answers).filter(x=>x!==null).length} of 5 answered</span>{#if ready}<button class="wizard-primary" onclick={()=>show('steps')}>Open my checklist →</button>{:else}<span>Your checklist opens after the last answer.</span>{/if}</div>
{:else}
 <div class="wizard-heading"><div><p class="flow-kicker">02 / INSTALLATION</p><h2>{current===steps.length?'You’re squared away.':'One step at a time.'}</h2><p>{current} of {steps.length} steps completed · {answers.game?'GAMMA':'Anomaly 1.5.3'}{answers.sota?' · SOTA UI':''}{answers.bodycam?' · Bodycam':''}</p></div><button class="wizard-link" onclick={()=>show('questions')}>Change my answers</button></div>
 <progress max={steps.length} value={current} aria-label="Installation progress"></progress>
 <div class="wizard-checklist">{#each steps as [id,text],i}<article bind:this={stepNodes[i]} class="wizard-step" class:active={i===current} class:complete={i<current} class:locked={i>current} aria-current={i===current?'step':undefined}><span class="wizard-step-number">{i<current?'✓':String(i+1).padStart(2,'0')}</span><div><h3>{titles[id]||id}</h3><p>{text}</p>{#if i===current}<label class="wizard-confirm"><input type="checkbox" checked={false} onchange={e=>check(i,e.currentTarget.checked)}/>I’ve completed this step</label>{:else if i<current}<button class="wizard-link" onclick={()=>check(i,false)}>Revisit this step</button>{:else}<small>Complete the previous step to continue.</small>{/if}</div></article>{/each}</div>
 {#if current===steps.length}<div class="wizard-complete" role="status"><h3>Checklist complete</h3><p>Your installation steps are checked off. Launch the game and test your setup.</p><button class="wizard-link" onclick={()=>{current=0;show('steps');}}>Start the checklist again</button></div>{/if}
 <div class="wizard-footer"><a href="#downloads" target="_blank" rel="noreferrer">Open mod and engine downloads ↗</a><a href="https://discord.com/channels/912320241713958912/1322655858240262304/1524208180135989459" target="_blank" rel="noreferrer">Magazine mod ↗</a></div>
{/if}
</section>
<style>
.install-wizard{margin:30px 0;border:5px solid transparent;border-image:url('/zonebench-preview/assets/field-kit/frame.svg') 12 / 5px / 0 stretch;background:#171d17;padding:26px;scroll-margin-top:125px}.wizard-invite,.wizard-heading{display:flex;align-items:center;justify-content:space-between;gap:25px}.install-wizard h2{font-size:25px;font-weight:500;margin:12px 0}.install-wizard p{color:var(--dim);font-size:13px;line-height:1.8}.wizard-invite p{max-width:620px}.wizard-primary{border:1px solid #dcb88e;background:#dcb88e;color:#161c16;padding:15px 20px;font:inherit;font-size:13px;cursor:pointer;white-space:nowrap}.wizard-link{border:0;background:none;color:var(--hot);font:inherit;font-size:12px;cursor:pointer;padding:7px 0}.wizard-questions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-top:22px}.wizard-question{padding:20px 18px 0;background:#101610;border:1px solid #49513f;display:flex;flex-direction:column}.wizard-question.answered{border-color:#8c9471}.wizard-badge{width:38px;height:34px;display:grid;place-items:center;border:1px solid #535f48;color:#b2c399;font-size:11px}.wizard-question h3{font-size:17px;line-height:1.5;font-weight:500}.wizard-question p{flex:1;margin-top:0}.wizard-answers{display:grid;grid-template-columns:1fr 1fr;margin:10px -18px 0}.wizard-answers button{padding:13px;border:1px solid #434d39;background:#20291c;color:var(--ink);cursor:pointer;font:inherit}.wizard-answers button.chosen{background:#dcb88e;color:#182016;border-color:#dcb88e}.wizard-footer{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:15px;margin-top:23px;font-size:12px;color:var(--dim)}.wizard-footer a{color:var(--hot)}progress{width:100%;height:6px;margin:18px 0;accent-color:#aabd8e}.wizard-checklist{display:grid;gap:12px}.wizard-step{display:flex;align-items:flex-start;gap:20px;padding:22px;background:#111810;border:1px solid #454d3d}.wizard-step-number{flex-shrink:0;color:#9dae86;font-size:18px;padding-top:4px}.wizard-step h3{margin:0;font-size:18px;font-weight:500}.wizard-step p{margin:10px 0}.wizard-step.active{border-color:#dcb88e;background:#252b20;box-shadow:inset 3px 0 #dcb88e}.wizard-step.locked{opacity:.38}.wizard-step.complete{opacity:.7}.wizard-step small{font-size:11px;color:var(--dim)}.wizard-confirm{display:flex;align-items:center;gap:12px;padding:12px 0 0;font-size:14px;color:var(--hot);cursor:pointer}.wizard-confirm input{width:19px;height:19px;accent-color:#dcb88e}.wizard-complete{padding:20px;border:1px solid #9cae80;background:#26301f;margin-top:20px}.wizard-heading>.wizard-link{flex-shrink:0}@media(max-width:900px){.wizard-questions{grid-template-columns:repeat(2,minmax(0,1fr))}.wizard-invite{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.install-wizard{padding:16px}.wizard-questions{grid-template-columns:1fr}.wizard-heading{align-items:flex-start;flex-direction:column}.wizard-primary{white-space:normal}.wizard-step{gap:12px;padding:16px}}
</style>
