<script>
 import {untrack} from 'svelte';
 let {workflow,rows=[],settings=null,onback,onopen}=$props();
 let model=$state(untrack(()=>settings?JSON.parse(JSON.stringify(settings)):null)),selected=$state(untrack(()=>rows)),report=$state(null),error=$state(''),busy=$state(false),notice=$state('');
 let records=$state(untrack(()=>workflow.packages().slice()));
 const fields={slots:'Storage pockets',pins:'Pocket positions',band:'Storage width',size:'Backpack capacity',cost:'Price',weight:'Weight',craft:'Crafting recipe',parts:'Repair parts',yield:'Dismantling returns',icon:'Texture',name:'Name',descr:'Description',grants:'Pouch slots',shelves:'Trader supplies'};
 function value(v){if(v===undefined)return 'Default';if(typeof v==='object')return JSON.stringify(v);return String(v);}
 async function inspect(){busy=true;error='';report=null;try{selected=await workflow.prepare(selected);report=workflow.review(selected,$state.snapshot(model));}catch(e){error=e.message;}finally{busy=false;}}
 async function finish(download){busy=true;error='';try{selected=await workflow.prepare(selected);report=workflow.review(selected,$state.snapshot(model));const saved=download?await workflow.download(selected,$state.snapshot(model)):workflow.savePackage(selected,$state.snapshot(model));model=JSON.parse(JSON.stringify(saved));notice=download?'Package downloaded. Replace its previous version in MO2.':'Package saved locally. You can reopen it from Saved packages.';}catch(e){error=e.message;}finally{busy=false;}}
</script>

<section class="package-page">
 <button class="flow-link" onclick={onback}>← Back to library</button>
 {#if !model}
  <div class="flow-heading"><p class="flow-kicker">YOUR WORKSPACE</p><h1>Saved packages</h1><p>Reopen a package to keep its identity, selections and version history.</p></div>
  {#each records as record (record.id)}<section class="package-record"><div><h2>{record.name}</h2><p>Version {record.version} · {record.items.length} items · {record.source==='adaptations'?'Adaptations':'My add-ons'}</p><span class:changed={workflow.packageStatus(record)!=='Up to date'}>{workflow.packageStatus(record)}</span></div><button class="tool primary" onclick={()=>onopen(record)}>Update package →</button></section>{/each}
  {#if !records.length}<p class="library-empty">Select items in a library and create your first package.</p>{/if}
 {:else}
  <div class="flow-heading"><p class="flow-kicker">PACKAGE BUILDER</p><h1>Review your package</h1><p>Only the selected items are included.</p></div>
  <div class="package-steps"><span>✓ Choose items</span><strong>02 · Review</strong><span>03 · Download</span></div>
  <details class="package-picker"><summary>Change included items</summary>{#each workflow.available(model.source) as row}<label><input type="checkbox" checked={selected.some(r=>r.kind===row.kind&&r.key===row.key)} onchange={e=>{selected=e.currentTarget.checked?[...selected,row]:selected.filter(r=>r.kind!==row.kind||r.key!==row.key);report=null;}}/>{window.EditorLibrary.label(row.item)} · {workflow.type(row)}</label>{/each}</details>
  <div class="package-columns"><section class="package-panel"><h2>What this package does</h2>
   {#each selected as row,i}<div class="package-item"><div><strong>{row.missing?row.name:window.EditorLibrary.label(row.item)}</strong><small>{row.missing?'Missing from your library':workflow.type(row)==='Mod edit'?'Changes existing item: '+row.item.id:workflow.type(row)==='Adaptation'?'Adapts existing item: '+row.item.id:'Adds a new item'}</small></div><button class="flow-link" disabled={busy} onclick={()=>{selected=selected.filter((_,at)=>at!==i);report=null;error='';}}>Remove from package</button></div>{/each}
   {#if !selected.length}<p>Select items from your library first.</p>{/if}
   <button class="tool" disabled={busy||!selected.length} onclick={inspect}>{busy?'Checking…':'Check selected items'}</button>
   {#if report}<p class="package-success">✓ Selected items passed export checks</p><details><summary>Review changes and files</summary>{#each report.items as item}<h3>{item.name}</h3>{#each item.changes as change}<div class="package-change"><strong>{fields[change.key]||change.key}</strong><span>{value(change.before)} → {value(change.after)}</span></div>{/each}{/each}<pre>{report.files.join('\n')}</pre></details>{/if}
  </section><aside class="package-panel"><h2>Package details</h2><label>Name<input bind:value={model.name} maxlength="100"/></label><label>Version<input bind:value={model.version} maxlength="32"/></label><h3>Installation</h3><p>Install below Squared Away{model.source==='adaptations'?' and the mods that supply these items':''} in MO2.</p><p>New items use this package's own IDs. Mod edits and adaptations keep the original IDs.</p>{#if report?.requiredAddons?.length}<h3>Required add-ons</h3>{#each report.requiredAddons as addon}<p>{addon.name} · {addon.version}</p>{/each}{/if}{#if model.exportedVersion}<p>Last downloaded: {model.exportedVersion}. Increase the version when publishing changes.</p>{/if}</aside></div>
  {#if error}<p class="package-error" role="alert">{error}</p>{/if}{#if notice}<p class="package-success" role="status">{notice}</p>{/if}
  <div class="package-footer"><div><strong>Squared Away {model.name} {model.version}.zip</strong><small>{selected.length} selected items</small></div><div><button class="tool" disabled={busy||!selected.length} onclick={()=>finish(false)}>Save package</button><button class="tool primary" disabled={busy||!selected.length} onclick={()=>finish(true)}>{busy?'Preparing…':'Save & download ZIP'}</button></div></div>
 {/if}
</section>

<style>
 .package-picker{padding:16px;margin-bottom:20px;border:1px solid #454d3f;background:#171d18}.package-picker label{display:flex;gap:10px;align-items:center;font-size:13px;padding:8px 0}.package-picker input{accent-color:var(--hot)}
 .package-steps{display:flex;gap:24px;flex-wrap:wrap;padding:18px 0;margin-bottom:20px;border-bottom:1px solid #464e40;color:var(--dim);font-size:13px}.package-steps strong{color:var(--hot)}.package-columns{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(240px,1fr);gap:20px}.package-panel{padding:22px;background:#171d18;border:1px solid #454d3f;min-width:0}.package-panel h2{font-size:19px;margin:0 0 18px}.package-panel h3{font-size:14px;margin-top:22px}.package-panel p{color:var(--dim);font-size:13px;line-height:1.7}.package-panel label{display:grid;gap:8px;font-size:13px;margin:16px 0}.package-panel input{width:100%;box-sizing:border-box;background:#101611;color:var(--ink);border:1px solid #555d4c;padding:12px;font:inherit}.package-item{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:15px 0;border-bottom:1px solid #3d4538;margin-bottom:12px}.package-item small,.package-footer small{display:block;color:var(--dim);margin-top:5px;font-size:12px}.package-item strong{font-size:14px}.package-item>div{min-width:0;overflow-wrap:anywhere}.package-change{display:grid;gap:5px;margin:12px 0;font-size:12px;overflow-wrap:anywhere}.package-change span{color:var(--dim)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.package-footer{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;padding:18px;margin-top:20px;background:#293024;border:2px solid #505648}.package-footer>div{overflow-wrap:anywhere;min-width:0}.package-footer button{margin:4px}.package-success{color:#aec597;padding:12px 0}.package-error{color:#efacbf;padding:12px;border-left:3px solid #c96480;background:#302127}.package-record{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:22px;background:#1a201a;border:1px solid #485040;margin-bottom:14px}.package-record h2{font-size:19px;margin:0}.package-record p{font-size:12px;color:var(--dim)}.package-record span{font-size:12px;color:#afc392}.package-record .changed{color:var(--hot)}@media(max-width:760px){.package-columns{grid-template-columns:1fr}.package-record,.package-item{align-items:flex-start;flex-direction:column}}
</style>
