(function(root){
'use strict';
let results=[],error='',checked=false,busy=false,generation=0,repaint=null;
const kinds=['rigs','boxes','pouches','packs','items'];
function imported(){return kinds.flatMap(k=>DB[k]||[]).filter(x=>x.communitySource);}
function paintBadge(){const count=results.length;for(const a of document.querySelectorAll('#site-nav a'))if(a.getAttribute('href')==='#community'){a.querySelector('.update-count')?.remove();if(count){const badge=document.createElement('span');badge.className='update-count';badge.textContent=count+' update'+(count===1?'':'s');a.appendChild(badge);}}}
async function check(){if(busy)return;const token=++generation;busy=true;error='';try{if(!Community.enabled){throw Error('Open the Community preview to check imported add-ons for updates.');}const mine=imported();if(!mine.length){results=[];checked=true;return;}let offset=0,all=[];while(true){const page=await Community.request('list',{mode:'public',offset});all.push(...page.items);offset+=page.items.length;if(!page.items.length||offset>=page.total)break;}if(token!==generation)return;results=all.filter(listing=>mine.some(it=>it.communitySource.id===listing.id&&it.communitySource.revision<listing.revision));checked=true;}catch(e){if(token===generation)error=e.message;}finally{busy=false;paintBadge();repaint?.();}}
function render(parent){const section=document.createElement('section');section.className='card update-panel';parent.appendChild(section);function draw(){section.replaceChildren();const h=document.createElement('h2');h.textContent='Imported add-on updates';section.appendChild(h);const b=document.createElement('button');b.className='tool';b.textContent=busy?'Checking…':'Check for updates';b.disabled=busy;b.onclick=async()=>{const promise=check();draw();await promise;if(section.isConnected)draw();};section.appendChild(b);const p=document.createElement('p');p.className='hint';p.textContent=error||(!imported().length?'No imported Community add-ons in this project.':checked?(results.length?'Review changes before choosing which items to update.':'No newer versions found among currently published add-ons.'):'Check for newer versions of the add-ons you imported.');section.appendChild(p);for(const listing of results){const row=document.createElement('div');row.className='community-actions';const name=document.createElement('span');name.textContent=listing.name+' · '+listing.version;row.appendChild(name);const review=document.createElement('button');review.className='tool primary';review.textContent='Compare update';review.onclick=async()=>{review.disabled=true;try{Community.preview(await Community.request('pack',{id:listing.id}));}catch(e){p.textContent=e.message;review.disabled=false;}};row.appendChild(review);section.appendChild(row);}}repaint=()=>{if(section.isConnected)draw();};draw();}
root.CommunityUpdates={check,render,paintBadge,async start(){if(imported().length&&Community.enabled)await check();},invalidate(){generation++;results=[];checked=false;error='';paintBadge();}};
})(globalThis);
