(function(root){
'use strict';
const state={game:'gamma',sota:false,devices:false,looting:false,bodycam:false},done=new Set();
const n=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function steps(s){return [
 ['mod','Install Squared Away through MO2. Replace the old installation and disable old copies or hotfixes.'],
 ['engine',s.bodycam?'Use the optional Bodycam engine for Squared Away 2.0.3 (DX11-AVX only) instead of the standard engine. Extract both bin and db/mods into Anomaly; keep the EXE and DB0 from the same ZIP. For PiP, also keep the external compatibility content required by Bodycam.':'Install the Squared Away 2.0.3 custom engine, also used by 2.0.6, in the Anomaly folder: bin/ for executables and PDB files, db/mods/ for the DB0. Back up the existing engine files first.'],
 ['mags',s.game==='zona'?'Keep ZONA V1.38 Magazines Redux and its installed magazine add-ons. Select Mags Redux ammo fix under ZONA compatibility. Do not select the GAMMA Mags Reloaded fix or install Dynamic Reload Speeds for this patch.':'Recommended for the baseline rigs and stock pouches: install Mags Reloaded Fork by Priler UPDATE 6 and its Dynamic Reload Speeds dependency. Select the optional Mags Reloaded ammo fix in the FOMOD with Mags Reloaded Fork by Priler UPDATE 6 and its Dynamic Reload Speeds dependency installed. It requires the 2.0.3 engine. Let Squared Away win their file conflicts in MO2.'],
 ...(s.game==='zona'?[['zona','Squared Away was built for GAMMA. ZONA compatibility covers the UI and magazine reload fixes; crafting recipes, repair parts, dismantling returns and trader settings may be wrong or unavailable in ZONA. Adapt them in ZoneBench using manual item IDs and verify the referenced items exist in ZONA.']]:[]),
 ...(s.game==='anomaly'?[['anomaly','Use Anomaly 1.5.3. GAMMA-specific crafting and trader content needs its separate dependencies; vanilla Anomaly does not supply them.']]:[]),
 ['sota',s.sota?'Select SOTA UI Compatibility ('+(s.game==='zona'?'ZONA':'GAMMA')+') in its matching compatibility group. SOTA UI and its usual requirements must already be installed. Do not combine GAMMA and ZONA patches.':'Leave the SOTA UI patch unchecked. Use the default UI option.'],
 ['hd',s.sota?'HD Inventory Icons Framework is required for correct inventory icons. Install only its SOTA-patched version.':'HD Inventory Icons Framework is required for correct inventory icons. Install only its non-SOTA version.'],
 ...(s.devices?[['devices','Select Wearable Devices support in the FOMOD, with the separate Wearable Devices pack installed.']]:[]),
 ...(s.looting?[['looting','Select Tarkov-like corpse looting only with Looting Takes Time Redux by Priler. Turn OFF its “Pre-sort items on grid” setting.']]:[]),
 ['order','Squared Away should be last in the MO2 left pane, with optional add-ons below it.'],
 ['newgame','If this is your first time installing Squared Away, a new game is required. If you played on a version before the 2.0 Update, a new game is also required. If you already have a playthrough on 2.0 or later and are only updating, you can continue that save.']
 ];}
function render(parent){const box=n('details');box.className='installation-checklist';box.appendChild(n('summary','Build your installation checklist'));const body=n('div');box.appendChild(body);body.appendChild(n('p','hint'));body.lastChild.textContent='Choose your setup. This checklist guides installation; it does not detect installed mods.';
 const label=n('label','Your game '),select=n('select');select.setAttribute('aria-label','Installation game');for(const [value,text] of [['gamma','GAMMA'],['zona','ZONA'],['anomaly','Anomaly 1.5.3']]){const o=n('option',text);o.value=value;select.appendChild(o);}select.value=state.game;label.appendChild(select);body.appendChild(label);
 const options=n('div');options.className='checklist-options';body.appendChild(options);for(const [key,text] of [['bodycam','Bodycam (DX11-AVX)'],['sota','SOTA UI'],['devices','Wearable Devices'],['looting','Looting Takes Time Redux']]){const l=n('label'),input=n('input');input.type='checkbox';input.checked=state[key];input.onchange=()=>{state[key]=input.checked;paint();};l.append(input,document.createTextNode(text));options.appendChild(l);}
 const list=n('div');body.appendChild(list);select.onchange=()=>{state.game=select.value;paint();};function paint(){list.replaceChildren();for(const [id,text] of steps(state)){const key=id+':'+text,l=n('label'),input=n('input');l.className='checklist-step';input.type='checkbox';input.checked=done.has(key);input.onchange=()=>input.checked?done.add(key):done.delete(key);l.append(input,n('span',text));list.appendChild(l);}}
 paint();const link=n('a','Download the baseline magazine mod');link.href='https://discord.com/channels/912320241713958912/1322655858240262304/1524208180135989459';link.target='_blank';link.rel='noopener noreferrer';link.className='tool';body.appendChild(link);body.appendChild(n('p','hint'));body.lastChild.textContent='Use the paired mod and engine links in Downloads. Checklist ticks last for this page session.';parent.appendChild(box);}
root.InstallationGuide={steps,render};
})(globalThis);
