/* Project history and item comparison. No account or server state is recorded. */
(function(root){
'use strict';
const kinds=['rigs','boxes','pouches','packs','items'];
const clone=x=>JSON.parse(JSON.stringify(x));
const stable=x=>JSON.stringify(sort(x));
function sort(x){if(Array.isArray(x))return x.map(sort);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])]));return x;}
const ignored=new Set(['iconNew','iconKept','communitySource','new','removed','edited','rows']);
function comparable(it){const out={};for(const [k,v] of Object.entries(it||{})){if(ignored.has(k))continue;if(k==='fit'&&(!v||(v.zoom??1)===1&&!(v.dx||0)&&!(v.dy||0)))continue;if(v===undefined)continue;out[k]=v;}return out;}
function differences(a,b){a=comparable(a);b=comparable(b);return [...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>stable(a[k])!==stable(b[k])).map(key=>({key,before:a[key],after:b[key]}));}
class History{
 constructor(limit=40,budget=32*1024*1024){this.limit=limit;this.budget=budget;this.reset({});}
 snapshot(db){const copy={...db};delete copy.files;delete copy.uibase;for(const kind of kinds)if(copy[kind])copy[kind]=copy[kind].map(it=>({...it,fit:it.fit||{zoom:1,dx:0,dy:0},...(kind==='rigs'?{rows:it.rows||Math.max(6,...(it.pins||[]).map(p=>p.row+Number(p.kind.split('x')[0])-1))}:{})}));return JSON.stringify(copy);}
 reset(db){this.current=this.snapshot(db);this.past=[];this.future=[];this.key=null;this.time=0;}
 record(db,key=null,now=Date.now()){const next=this.snapshot(db);if(next===this.current)return false;const merge=key!==null&&key===this.key&&now-this.time<650&&this.past.length&&!this.future.length;if(!merge)this.past.push(this.current);this.current=next;this.future=[];this.key=key;this.time=now;let bytes=this.past.reduce((n,s)=>n+s.length*2,0);while(this.past.length>1&&(this.past.length>this.limit||bytes>this.budget))bytes-=this.past.shift().length*2;return true;}
 move(direction){const from=direction==='undo'?this.past:this.future,to=direction==='undo'?this.future:this.past;if(!from.length)return null;to.push(this.current);this.current=from.pop();this.key=null;return JSON.parse(this.current);}
}
let history=null,defaults=null,updating=false;
const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=String(text);return e;};
function button(label,fn){const b=node('button','tool',label);b.type='button';b.onclick=fn;return b;}
function base(kind,id){return defaults?.[kind]?.find(it=>it.id===id);}
function status(kind,it){const original=base(kind,it.id);return original?(differences(original,it).length?'Customized':'Default'):(it.communitySource?'Imported':'Custom');}
function toolbar(){if(!history)return;const undo=document.querySelector('#btnUndo'),redo=document.querySelector('#btnRedo');if(undo){undo.disabled=!history.past.length;redo.disabled=!history.future.length;}}
function record(key){if(!history||updating)return;history.record(DB,key);toolbar();markRows();const badge=document.querySelector('.item-change-tools>.change-badge');const it=DB[TAB]?.find(x=>x.id===SEL[TAB]);if(badge&&it)badge.textContent=status(TAB,it);}
function markRows(){const rows=document.querySelectorAll('#list .row');rows.forEach((row,i)=>{const it=DB[TAB]?.[i];if(!it)return;let badge=row.querySelector('.change-badge');const text=status(TAB,it);if(text==='Default'){badge?.remove();return;}if(!badge){badge=node('span','change-badge');row.querySelector('.tx').appendChild(badge);}badge.textContent=text;});}
function move(direction){if(!history)return;record();const restored=history.move(direction);if(!restored)return;updating=true;DB={...restored,files:DB.files,uibase:DB.uibase};EMIT.craftOrder=DB.craftOrder||SEED.craftOrder||[];for(const k of kinds)if(!DB[k]?.some(it=>it.id===SEL[k]))SEL[k]=DB[k]?.[0]?.id;INCOMING=null;SHARE_PICK=null;CommunityUpdates.invalidate();DIRTY=true;render();scheduleKeep();updating=false;toolbar();}
function compare(parent,kind,before,after,left='Current',right='Incoming'){
 if(kind!=='settings'){const grid=node('div','compare-pair');for(const [label,it] of [[left,before],[right,after]]){const card=node('section','card');card.appendChild(node('h3',null,label));if(it){card.appendChild(AddonPreview.picture({kind,item:it}));if(['rigs','boxes','pouches'].includes(kind))card.appendChild(AddonPreview.layoutView({kind,item:it}));}else card.appendChild(node('p','hint','Not present'));grid.appendChild(card);}parent.appendChild(grid);}
 const changes=differences(before,after);if(!changes.length){parent.appendChild(node('p','hint','No item setting differences.'));return;}
 const table=node('table','comparison-table'),head=node('tr');for(const title of ['Setting',left,right])head.appendChild(node('th',null,title));const thead=node('thead');thead.appendChild(head);table.appendChild(thead);const body=node('tbody');
 const names={cost:'Price (RU)',weight:'Weight (kg)',kg:'Contents weight limit (kg)',icon:'Inventory texture',cellw:'Inventory width',cellh:'Inventory height',inw:'Storage width',inh:'Storage height',slots:'Storage pockets',pins:'Pocket positions',grants:'Pouch expansion',takes:'Allowed contents group',craft:'Crafting',descr:'Description',fit:'Texture placement',size:'Backpack storage',own:'Enabled overrides'};
 for(const change of changes){const row=node('tr');row.appendChild(node('th',null,names[change.key]||change.key));for(const value of [change.before,change.after]){const cell=node('td');if(change.key==='icon')cell.textContent=value?'Texture supplied':'No texture';else cell.appendChild(node('pre',null,value===undefined?'Not set':typeof value==='object'?JSON.stringify(value,null,2):String(value)));row.appendChild(cell);}body.appendChild(row);}table.appendChild(body);const wrap=node('div','comparison-scroll');wrap.appendChild(table);parent.appendChild(wrap);
}
function itemTools(P,it){const kind=TAB,original=base(kind,it.id),bar=node('div','item-change-tools');bar.appendChild(node('span','change-badge',status(kind,it)));if(original){const compareButton=button('Compare with default',()=>{const d=node('dialog','addon-dialog');d.setAttribute('aria-label','Compare with mod defaults');const head=node('div','addon-dialog-header');head.append(node('strong',null,'Changes to '+(it.name||it.id)),button('Close comparison',()=>d.close()));d.appendChild(head);const body=node('div','addon-dialog-body');compare(body,kind,original,it,'Mod default','Your item');body.appendChild(button('Reset this item to default',()=>{DB[kind][DB[kind].indexOf(it)]=clone(original);if(kind==='packs'&&DB.packEdited)delete DB.packEdited[it.id];DB.removed=(DB.removed||[]).filter(x=>x.id!==it.id);touch();d.close();render();}));body.appendChild(node('p','hint','Resets this item only. Shared container rules and global drop settings stay as configured. Undo restores your edits.'));d.appendChild(body);d.addEventListener('close',()=>d.remove());document.body.appendChild(d);d.showModal();});bar.appendChild(compareButton);}else bar.appendChild(node('span','hint','No matching item in the mod defaults.'));const heading=P.querySelector('h1');heading?heading.after(bar):P.prepend(bar);}
function capacity(kind,it,db){
 let cells=null;if(['rigs','boxes','pouches'].includes(kind)){const {rects}=AddonPreview.geometry({kind,item:it});const occupied=new Set();for(const r of rects)for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)occupied.add(x+','+y);cells=occupied.size;}else if(kind==='packs')cells=(EMIT.packSize(it.size)||EMIT.packSize(db.packDefault))?.cells??null;
 const footprint=Number(it.cellw)*Number(it.cellh);return {cells,footprint:footprint>0?footprint:null,kg:kind==='boxes'?it.kg:undefined};
}
function efficiency(parent,kind,it){const data=capacity(kind,it,DB);if(data.cells===null)return;const section=node('section','efficiency-summary');section.appendChild(node('h3',null,kind==='pouches'?'Expansion summary':'Storage efficiency'));section.appendChild(node('p',null,(kind==='pouches'?'Adds ':'Provides ')+data.cells+' usable cells'));section.appendChild(node('p','hint',data.footprint?'Uses '+data.footprint+' inventory cells · '+(data.cells/data.footprint).toFixed(1)+'× storage / footprint':'Inventory footprint inherited from the original mod'));if(kind==='boxes')section.appendChild(node('p','hint',data.kg==null?'No contents weight limit':data.kg+' kg contents limit'));else section.appendChild(node('p','hint','Actor carry weight still applies.'));parent.appendChild(section);}
function importReview(parent,incoming){
 const replacing=incoming.items.filter(e=>e.take&&e.how==='replace'&&DB[e.kind]?.some(x=>x.id===e.item.id));const selected=incoming.items.filter(e=>e.take);const renamed=selected.filter(e=>e.how!=='replace'&&DB[e.kind]?.some(x=>x.id===e.item.id));parent.appendChild(node('p','import-summary',`${selected.length-replacing.length-renamed.length} added · ${replacing.length} replaced · ${renamed.length} added with a new ID`));
 for(const entry of selected){const current=DB[entry.kind]?.find(x=>x.id===entry.item.id);const d=node('details','import-comparison');d.appendChild(node('summary',null,(entry.item.name||entry.item.id)+' — '+(current?(entry.how==='replace'?'replace existing item':'keep both'):'add new item')));const content=node('div');d.appendChild(content);let built=false;d.ontoggle=()=>{if(d.open&&!built){built=true;compare(content,entry.kind,current,entry.item);if(entry.kind==='boxes'){content.appendChild(node('h3',null,'Allowed contents rules'));const rules=node('pre');rules.textContent=JSON.stringify({Current:DB.families?.[current?.takes]??null,Incoming:incoming.families?.[entry.item.takes]??null},null,2);content.appendChild(rules);}}};parent.appendChild(d);}
 return replacing.length;
}
root.Workbench={undo:()=>move('undo'),History,differences,capacity,compare,status,record,markRows,itemTools,efficiency,importReview,
 setDefaults(db){defaults=clone(db);delete defaults.files;delete defaults.uibase;},
 init(){history=new History();history.reset(DB);const tools=document.querySelector('#project-tools'),save=document.querySelector('#btnLoad');const undo=button('Undo',()=>move('undo'));undo.id='btnUndo';undo.title='Undo project edit (Ctrl+Z outside text fields). History lasts for this tab.';const redo=button('Redo',()=>move('redo'));redo.id='btnRedo';redo.title='Redo project edit (Ctrl+Shift+Z or Ctrl+Y outside text fields).';tools.insertBefore(undo,save);tools.insertBefore(redo,save);toolbar();markRows();document.addEventListener('keydown',e=>{if(document.body.classList.contains('site-page')||!(e.ctrlKey||e.metaKey)||e.altKey||e.target.closest('input,textarea,select,[contenteditable=true],dialog'))return;if(e.key.toLowerCase()==='z'||e.key.toLowerCase()==='y'){e.preventDefault();move(e.shiftKey||e.key.toLowerCase()==='y'?'redo':'undo');}});},
 changes(P){P.appendChild(node('h1',null,'Your changes'));CommunityUpdates.render(P);P.appendChild(node('p','hint','Compared with this release’s defaults. Undo and redo are available while this tab stays open.'));let count=0;for(const kind of kinds){for(const it of DB[kind]||[]){if(status(kind,it)==='Default')continue;count++;const b=button((it.name||it.id)+' · '+status(kind,it),()=>{SEL[kind]=it.id;Site.go(kind);});P.appendChild(b);}for(const it of defaults?.[kind]||[]){if(DB[kind]?.some(x=>x.id===it.id))continue;count++;const row=node('p',null,(it.name||it.id)+' · Removed ');row.appendChild(button('Restore item',()=>{(DB[kind]||(DB[kind]=[])).push(clone(it));DB.removed=(DB.removed||[]).filter(x=>x.id!==it.id);touch();render();}));P.appendChild(row);}}if(!count)P.appendChild(node('p','hint','No item changes.'));const globalKeys=['families','drops','shelves','cond','packDefault','packKinds'];const changed=globalKeys.filter(k=>stable(DB[k])!==stable(defaults?.[k]));for(const key of changed){const labels={families:'Container contents rules',drops:'NPC drop chances',shelves:'Trader supplies',cond:'Dropped condition',packDefault:'Default backpack capacity',packKinds:'Backpack categories'};const d=node('details','import-comparison');d.appendChild(node('summary',null,labels[key]));compare(d,'settings',{[key]:defaults?.[key]},{[key]:DB[key]},'Mod default','Your settings');P.appendChild(d);}}
};
})(globalThis);
