<script>
 import {addonFilename} from '../lib/guided-install.mjs';
 import {onMount} from 'svelte';
 import {recipeRequirements,addonLink} from '../lib/addon-requirements.mjs';
 import AddonItemDetails from '../components/AddonItemDetails.svelte';
 import AddonCover from '../components/AddonCover.svelte';
 import {filterListings,loadLibrary} from '../lib/addon-browser.mjs';
 import {downloadedAddons,recordDownload} from '../lib/addon-downloads.mjs';
 let records=$state([]),loading=$state(true),error=$state(''),query=$state(''),kind=$state(''),sort=$state('newest'),downloadedOnly=$state(false),downloads=$state([]),user=$state(null),limit=$state(12),selected=$state(null),busy=$state(false),downloadError=$state(''),success=$state('');
 let results=$derived(filterListings(records,{query,kind,sort,downloadedOnly,downloads}));
 const labels={rigs:'Rigs',boxes:'Containers',pouches:'Pouches',packs:'Backpacks',items:'Other items'};
 let inspected=$state(null);let requestedError=$state('');
 let requirements=$derived(recipeRequirements(selected?.pack,downloads));
 let stopped=false;
 function accountChanged(){user=window.Community.user;downloads=downloadedAddons(user);}
 async function hydrate(record){try{const result=await window.Community.request('pack',{id:record.listing.id});window.ZB.validateAddon(result.pack);if(stopped)return;records=records.map(r=>r.listing.id===record.listing.id?{...r,result,error:''}:r);return result;}catch(e){if(!stopped)records=records.map(r=>r.listing.id===record.listing.id?{...r,error:e.message}:r);}}
 async function load(){loading=true;error='';try{const list=await loadLibrary(window.Community,rows=>records=rows,{get aborted(){return stopped;}});let next=0;async function worker(){while(next<list.length&&!stopped)await hydrate(list[next++]);}await Promise.all([worker(),worker()]);const requested=location.hash.match(/^#addons\/view\/([a-zA-Z0-9_-]+)$/)?.[1];if(requested&&!stopped){const record=records.find(r=>r.listing.id===requested);if(record)await open(record);else requestedError='This add-on is no longer publicly available. Your downloaded files are unchanged.';}}catch(e){error=e.message;}finally{loading=false;}}
 onMount(()=>{stopped=false;window.addEventListener('zonebench-account-changed',accountChanged);load();window.Community.refresh().then(u=>{if(!stopped){user=u;downloads=downloadedAddons(u);}}).catch(()=>{});return ()=>{stopped=true;window.removeEventListener('zonebench-account-changed',accountChanged);};});
 async function open(record){downloadError='';success='';selected=record.result||await hydrate(record);}
 function modal(node){node.showModal();return {destroy(){node.close();}};}
 function close(){if(!busy){selected=null;if(location.hash.startsWith('#addons/view/'))history.replaceState({},'','#addons');}}
 async function download(){busy=true;downloadError='';success='';try{const result=await window.CommunityDownload.build(selected),blob=await result.blob,url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=addonFilename(selected.listing.name,selected.listing.version);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);success='ZIP prepared. Install it as a separate mod below Squared Away in MO2.';if(user){try{recordDownload(user,result.manifest,{listingId:selected.listing.id,revision:selected.listing.revision});downloads=downloadedAddons(user);window.dispatchEvent(new Event('zonebench-downloads-changed'));}catch{success+=' Your download history could not be saved in this browser.';}}}catch(e){downloadError=e.message;}finally{busy=false;}}
 function imported(){const result=selected;selected=null;window.Community.preview(result);}
</script>
<section class="gear-browser">
 <div class="gear-heading"><div><p class="flow-kicker">THE COMMUNITY WORKBENCH</p><h1>Gear made for your Zone.</h1><p>Find a new favourite. Inspect its pockets, check the requirements, then make room for it.</p></div><a class="gear-button" href="#editor/create">Create an add-on ↗</a></div>
 <nav class="gear-tabs" aria-label="Add-on library"><button class:active={!downloadedOnly} onclick={()=>{downloadedOnly=false;limit=12;}}>Browse all</button><button class:active={downloadedOnly} onclick={()=>{downloadedOnly=true;limit=12;}}>My downloads <span>{downloads.length}</span></button><button onclick={()=>window.Site.addons('mine')}>My published add-ons ↗</button>{#if user?.moderator}<button onclick={()=>window.Site.addons('moderation')}>Moderation ↗</button>{/if}</nav>
 {#if requestedError}<p class="gear-notice" role="status">{requestedError}</p>{/if}<div class="gear-browser-columns"><aside class="gear-filters"><span class="fabric-label">FIND YOUR GEAR</span><label>Search<input type="search" placeholder="Name, creator or item…" bind:value={query} oninput={()=>limit=12}/></label><p>Item type</p><button class:active={!kind} onclick={()=>{kind='';limit=12;}}>All equipment</button>{#each Object.entries(labels) as [id,label]}<button class:active={kind===id} onclick={()=>{kind=id;limit=12;}}>{label}</button>{/each}<div class="gear-filter-note">Inspect before installing.<br/>Each pack shows its actual item textures and storage layouts.</div></aside>
 <div class="gear-results"><div class="gear-results-bar"><p role="status">{loading?'Loading the library…':`${results.length} add-on${results.length===1?'':'s'}`}</p><label>Sort by<select bind:value={sort}><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="creator">Creator A–Z</option><option value="items">Most items</option></select></label></div>
 {#if error}<div class="gear-empty"><h2>The library could not load.</h2><p>{error}</p><button onclick={load}>Try again</button></div>{/if}
 {#if downloadedOnly&&!user}<div class="gear-empty"><h2>Keep your discoveries together.</h2><p>Sign in to remember downloads in this browser and use their items in your crafting recipes.</p><a href="https://fomok.github.io/zonebench/#account" target="_blank" rel="noreferrer" class="gear-button">Sign in on ZoneBench ↗</a><p>After signing in, refresh this preview to load your account.</p></div>{:else if !loading&&!results.length}<div class="gear-empty"><h2>{downloadedOnly?'Your next find belongs here.':'No gear found.'}</h2><p>{downloadedOnly?'Add-ons downloaded while signed in appear here.':'Try another search or browse all equipment.'}</p><button onclick={()=>{query='';kind='';downloadedOnly=false;}}>Browse all add-ons</button></div>{/if}
 <div class="gear-cards">{#each results.slice(0,limit) as record}{@const l=record.listing}{@const entries=record.result?.pack.items||[]}<article class="gear-card"><button class="gear-card-open" onclick={()=>open(record)} aria-label={`Inspect ${l.name}`}><AddonCover {entries} title={l.name}/><div class="gear-card-copy"><div class="gear-card-meta"><span>{entries.length||l.itemCount||'…'} items</span><span>v{l.version}</span></div><h2>{l.name}</h2><p class="gear-author">by {l.author}</p><p class="gear-excerpt">{l.description||'Open this add-on to explore its equipment.'}</p><div class="gear-tags">{#each [...new Set(entries.map(x=>x.kind))] as k}<span>{labels[k]||k}</span>{/each}</div></div></button><div class="gear-card-footer"><span>{downloads.some(d=>d.listingId===l.id)?(downloads.some(d=>d.listingId===l.id&&d.revision<l.revision)?'↑ Update available':'↓ In your downloads'):l.dependencies?'Requirements listed':'Community add-on'}</span><button onclick={()=>open(record)}>{record.error?'Retry preview':'View add-on →'}</button></div>{#if record.error}<p class="gear-inline-error">Preview unavailable. Select Retry preview.</p>{/if}</article>{/each}</div>
 {#if results.length>limit}<button class="gear-more" onclick={()=>limit+=12}>Show more add-ons</button>{/if}
 </div></div>
</section>
{#if selected}{@const listing=selected.listing}{@const eligibility=window.CommunityDownload.eligibility(selected.pack)}
 <dialog class="gear-detail" aria-label={listing.name} use:modal oncancel={e=>{if(busy)e.preventDefault();else close();}}><header><span>ADD-ON / {selected.pack.items.length} ITEMS</span><button onclick={close} disabled={busy} aria-label="Close add-on">✕</button></header><div class="gear-detail-body"><div class="gear-detail-title"><AddonCover entries={selected.pack.items} title={listing.name}/><div><p class="flow-kicker">BY {listing.author} · VERSION {listing.version}</p><h2>{listing.name}</h2><a href={addonLink(listing.id)}>Direct link to this add-on ↗</a><p>{listing.description||'No description supplied.'}</p></div></div>
 <div class="gear-detail-columns"><div><h3>Inside this add-on</h3><p class="gear-muted">Select an item to inspect its layout, price, recipe and settings.</p><div class="gear-item-tiles">{#each selected.pack.items as entry}<button onclick={()=>inspected=entry}><AddonCover entries={[entry]}/><strong>{entry.item.name||entry.item.id}</strong><small>{labels[entry.kind]}</small></button>{/each}</div></div><aside class="gear-install"><span class="fabric-label">TAKE IT INTO THE ZONE</span><h3>Requirements</h3><p><strong>Squared Away</strong> with independent add-on support, its matching engine and HD Inventory Icons Framework.</p><p>{listing.dependencies||'No extra requirements listed by the creator.'}</p>{#if requirements.length}<div class="gear-required-addons"><h4>Recipes need other add-ons</h4><p>Install these too if you want to craft the items listed.</p>{#each requirements as requirement}<div><strong>{requirement.name}</strong>{#if requirement.version}<small>Recipe created with version {requirement.version}</small>{/if}<small>Used by: {requirement.items.join(', ')}</small><small>{requirement.downloadedVersion?'In your download history: '+requirement.downloadedVersion:'Not in your download history'}</small>{#if requirement.link}<a href={requirement.link} onclick={close}>View required add-on →</a>{/if}</div>{/each}<p>Download history does not confirm installation in MO2.</p></div>{/if}{#if eligibility.ok}<button class="gear-download" disabled={busy} onclick={download}>{busy?'Preparing your ZIP…':'↓ Download add-on ZIP'}</button><ol><li>Install the ZIP through MO2.</li><li>Place it below Squared Away and its patches.</li><li>Enable it alongside your other independent add-ons.</li></ol><p class="gear-muted">Requires the independent add-on test version while this feature is in preview.</p>{:else}<p class="gear-notice">{eligibility.reason}</p>{/if}<button class="gear-import" disabled={busy} onclick={imported}>Open in editor →</button><p class="gear-muted">Editor import lets you choose and customize items before exporting.</p>{#if !user}<a href="https://fomok.github.io/zonebench/#account" target="_blank" rel="noreferrer">Sign in on ZoneBench to remember downloads ↗</a><p class="gear-muted">Then refresh this preview to load your account.</p>{:else}<p class="gear-muted">Downloads are remembered for your account in this browser. This does not detect your MO2 installation.</p>{/if}{#if success}<p class="gear-success" role="status">{success}</p>{/if}{#if downloadError}<p class="gear-inline-error" role="alert">{downloadError}</p>{/if}</aside></div></div></dialog>
{/if}

{#if inspected&&selected}<AddonItemDetails entry={inspected} pack={selected.pack} closed={()=>inspected=null}/>{/if}
